import type { HomePageContent } from './types';

export const homeContent: Pick<HomePageContent, 'hero' | 'intro' | 'partners' | 'results' | 'services' | 'projects' | 'testimonials' | 'recentPosts'> = {
  hero: {
    headline: "We Deliver and Care",
    integrations: [
      { name: "Kubernetes",  src: "/logos/kubernetes.svg",  alt: "Kubernetes" },
      { name: "AWS",         src: "/logos/aws.svg",         alt: "AWS" },
      { name: "Databricks",  src: "/logos/databricks.svg",  alt: "Databricks" },
      { name: "Azure",       src: "/logos/azure.svg",       alt: "Microsoft Azure" },
      { name: "Informatica", src: "/logos/informatica.png", alt: "Informatica" },
      { name: "Kong",        src: "/logos/kong.svg",        alt: "Kong" },
      { name: "Salesforce",  src: "/logos/salesforce.svg",  alt: "Salesforce" },
      { name: "MuleSoft",    src: "/logos/mulesoft.svg",    alt: "MuleSoft" },
      { name: "Claude",      src: "/logos/claude.svg",      alt: "Anthropic Claude" },
    ],
  },
  intro: {
    eyebrow: "Who we are",
    headline: [
      { text: "Where integration and AI make " },
      { text: "stronger businesses", highlight: true },
    ],
    paragraphs: [
      "Florence Next, part of Sirocco Group, is an IT Enterprise Consultancy company specialized in Integration and AI solutions that drive digital transformation.",
      "Our certified team of Enterprise Architects, Integration Experts, and AI Engineers helps organizations connect systems, automate processes, and unlock the power of intelligent data — from strategy to execution.",
    ],
  },
  partners: {
    partners: [
      {
        id: "mulesoft",
        name: "MuleSoft",
        logoSrc: "/logos/mulesoft.svg",
        logoAlt: "MuleSoft",
        logoWidth: 140,
        logoHeight: 40,
        title: "Mulesoft Premiere Partner",
        description: "We provide top-tier integration expertise to seamlessly and securely connect business systems, accelerating digital transformation.",
      },
      {
        id: "salesforce",
        name: "Salesforce",
        logoSrc: "/logos/salesforce.svg",
        logoAlt: "Salesforce",
        logoWidth: 90,
        logoHeight: 64,
        title: "Salesforce Summit Partner",
        description: "Leading digital transformation with innovative, tailor-made solutions that place the customer at the center for a truly cutting-edge experience.",
      },
      {
        id: "kong",
        name: "Kong",
        logoSrc: "/logos/kong.svg",
        logoAlt: "Kong",
        logoWidth: 120,
        logoHeight: 40,
        title: "Kong Partner",
        description: "Implementing scalable and secure API solutions, we foster an agile architecture that enhances performance and drives innovation in business processes.",
      },
      {
        id: "azure",
        name: "Microsoft Azure",
        logoSrc: "/logos/azure.svg",
        logoAlt: "Microsoft Azure",
        logoWidth: 120,
        logoHeight: 36,
        title: "Azure Partner",
        description: "Implementing scalable and secure API solutions, we foster an agile architecture that enhances performance and drives innovation in business processes.",
      },
      {
        id: "semarchy",
        name: "Semarchy",
        logoSrc: "/logos/semarchy.png",
        logoAlt: "Semarchy",
        logoWidth: 140,
        logoHeight: 36,
        title: "Semarchy Partner",
        description: "Implementing scalable and secure API solutions, we foster an agile architecture that enhances performance and drives innovation in business processes.",
      },
    ],
    ctaCard: {
      imageSrc: "/images/cta-callback.jpg",
      imageAlt: "Florence Next consultant",
      headline: "Free advice.\nBook a callback",
      ctaLabel: "Let's Talk",
      ctaHref: "/contact",
    },
  },
  results: {
    eyebrow: "Why choose us",
    headline: [
      { text: "Results that we " },
      { text: "successfully deliver", highlight: true },
    ],
    photo: {
      src: "/images/results-photo.jpg",
      alt: "Professional reviewing data on a tablet",
    },
    stats: [
      {
        id: "projects",
        label: "Projects completed",
        value: "40+",
        description: "Over 40 successful projects delivered to our clients worldwide.",
      },
      {
        id: "csat",
        label: "Customer Satisfaction CSAT",
        value: "4.9/5",
        description: "Don't trust us, ask our clients.",
      },
      {
        id: "integrated",
        label: "Integrated systems",
        value: "250+",
        description: "Deep expertise across platforms — we speak every system language.",
      },
    ],
    illustration: {
      src: "/images/results-illustration.svg",
      alt: "Data dashboard illustration",
    },
  },
  services: {
    eyebrow: "Our services",
    headline: [
      { text: "Digital services to " },
      { text: "grow your business", highlight: true },
    ],
    services: [
      {
        id: "ai-integration-assessment",
        title: "AI & Integration Assessment",
        description:
          "We evaluate your systems and data readiness for AI adoption, ensuring seamless integration across platforms. Our assessment identifies opportunities to automate, connect, and optimize your ecosystem for smarter, faster business outcomes.",
        tags: [
          "AI Readiness",
          "Automation Strategy",
          "Data Optimization",
          "Intelligent Ecosystem",
          "System Integration",
        ],
      },
      {
        id: "staff-augmentation",
        title: "Staff Augmentation",
        description:
          "We supply specialized professionals who quickly integrate with your team, increasing flexibility and filling skill gaps without lengthy hiring processes. This approach accelerates projects and ensures high-quality results.",
        tags: [
          "Flexible Workforce",
          "IT Staffing",
          "Scalable Resources",
          "Skilled Professionals",
          "Team Integration",
        ],
      },
      {
        id: "full-project-management",
        title: "Full-Project Management",
        description:
          "We handle the entire project lifecycle from planning to delivery, ensuring timely completion, budget adherence, and high standards. By managing coordination, risk mitigation, and strategic oversight, we let you focus on your core business.",
        tags: [
          "Agile",
          "End-to-end Management",
          "Project Coordination",
          "Risk Mitigation",
          "Strategic Oversight",
        ],
      },
      {
        id: "consulting-packages",
        title: "Consulting Packages",
        description:
          "We deliver fixed-scope consulting packages tailored to defined business challenges, providing senior expertise without long-term commitments. Each package combines clear deliverables, agreed timelines, and a focused team to accelerate decisions and reduce risk.",
        tags: [
          "Fixed Scope",
          "Senior Expertise",
          "Defined Deliverables",
          "Strategic Guidance",
          "Quick Engagement",
        ],
      },
    ],
    ctaLabel: "View all services",
    ctaHref: "/services",
  },
  projects: {
    eyebrow: "Selected Works",
    headline: [
      { text: "Trusted " },
      { text: "by", highlight: true },
    ],
    subhead: "More than 6 years of success stories",
    projects: [
      {
        id: "etoro",
        brand: "eToro",
        projectName: "Customer 360",
        category: "System Integration",
        logoSrc: "/projects/etoro-logo.png",
        logoWidth: 1547,
        logoHeight: 485,
        logoMaxHeight: 56,
        bgColor: "#0F2A33",
        href: "/projects/etoro-customer-360",
      },
      {
        id: "aspia",
        brand: "Aspia",
        projectName: "System Foundation",
        category: "System Integration",
        logoSrc: "/projects/aspia-logo.webp",
        logoWidth: 1191,
        logoHeight: 842,
        logoMaxHeight: 64,
        bgColor: "#2D0E1F",
        href: "/projects/aspia-system-foundation",
      },
      {
        id: "visma",
        brand: "Visma Amili Oy",
        projectName: "Agent AI",
        category: "Data foundation AI",
        logoSrc: "/projects/visma-logo.png",
        logoWidth: 1550,
        logoHeight: 297,
        logoMaxHeight: 48,
        bgColor: "#4A5C3A",
        href: "/projects/visma-agent-ai",
      },
      {
        id: "mhra",
        brand: "MHRA",
        projectName: "REST API Ecosystem",
        category: "API Integration",
        logoSrc: "/projects/mhra-logo.png",
        logoWidth: 2047,
        logoHeight: 687,
        logoMaxHeight: 36,
        bgColor: "#3F3825",
        href: "/projects/mhra-rest-api-ecosystem",
      },
      {
        id: "hanza",
        brand: "Hanza",
        projectName: "Supplier Management",
        category: "EDI integration",
        logoSrc: "/projects/hanza-logo.png",
        logoWidth: 1548,
        logoHeight: 241,
        logoMaxHeight: 56,
        bgColor: "#1F1A35",
        href: "/projects/hanza-supplier-management",
      },
      {
        id: "kone",
        brand: "Kone",
        projectName: "Data Monetizations",
        category: "API as a Product",
        logoSrc: "/projects/kone-logo.png",
        logoWidth: 400,
        logoHeight: 202,
        logoMaxHeight: 56,
        bgColor: "#4A0E12",
        href: "/projects/kone-data-monetizations",
      },
    ],
  },
  testimonials: {
    illustrationSrc: "/testimonials-illustration.svg",
    testimonials: [
      {
        id: "matthew-delaney",
        quote:
          "Florence Next has provided outstanding support in the Nordics and together we have helped several of our very strategic clients to achieve their goals.",
        authorName: "Matthew Delaney",
        authorRole: "Mulesoft Nordics Professional Services Lead",
      },
      {
        id: "yorai-ben-haim",
        quote:
          "Florence Next enabled us to unify data from numerous sources, automate critical workflows, and expand the reach and richness of our AI capabilities. Their partnership has been instrumental in driving efficiency and intelligent decision-making across the business",
        authorName: "Yorai Ben Haim",
        authorRole: "Director of Business Operations Technology",
      },
    ],
  },
  recentPosts: {
    eyebrow: "Recent Posts",
    headline: [
      { text: "Latest news and " },
      { text: "industry insights", highlight: true },
    ],
    posts: [
      {
        id: "mulesoft-4-migration-guidance",
        title: "Mulesoft 4 migration guidance",
        excerpt:
          "We bring deep, functional expertise, but are known for our holistic perspective: we capture value across boundaries…",
        category: "Company",
        date: "2024-11-20",
        author: "Florence Next",
        imageSrc: "/posts/mulesoft-4-migration-guidance.jpg",
        href: "/blog/mulesoft-4-migration-guidance",
      },
      {
        id: "florence-next-health-check-connector",
        title: "Introducing Florence Next Health Check connector",
        excerpt:
          "We bring deep, functional expertise, but are known for our holistic perspective: we capture value across boundaries…",
        category: "Lifestyle",
        date: "2024-11-20",
        author: "Florence Next",
        imageSrc: "/posts/florence-next-health-check-connector.png",
        href: "/blog/florence-next-health-check-connector",
      },
      {
        id: "mule-java-sdk-and-xml-sdk",
        title: "Some thoughts about Mule Java SDK and XML SDK",
        excerpt:
          "We bring deep, functional expertise, but are known for our holistic perspective: we capture value across boundaries…",
        category: "Social Media",
        date: "2024-11-20",
        author: "Florence Next",
        imageSrc: "/posts/mule-java-sdk-and-xml-sdk.png",
        href: "/blog/mule-java-sdk-and-xml-sdk",
      },
      {
        id: "digital-transformation-covid-19",
        title: "Digital Transformation Stories During COVID-19",
        excerpt:
          "We bring deep, functional expertise, but are known for our holistic perspective: we capture value across boundaries…",
        category: "Lifestyle",
        date: "2024-11-20",
        author: "Florence Next",
        imageSrc: "/posts/digital-transformation-covid-19.jpg",
        href: "/blog/digital-transformation-covid-19",
      },
    ],
  },
};
